export const WORKSPACE_CREATE_REQUEST = "WORKSPACE_CREATE_REQUEST";
export const WORKSPACE_CREATE_SUCCESS = "WORKSPACE_CREATE_SUCCESS";
export const WORKSPACE_CREATE_FAILURE = "WORKSPACE_CREATE_REQUEST";



export const TASK_CREATE_REQUEST = "TASK_CREATE_REQUEST";
export const TASK_CREATE_SUCCESS = "TASK_CREATE_SUCCESS";
export const TASK_CREATE_FAILURE = "TASK_CREATE_REQUEST";

export const TASK_UPDATE_REQUEST = "TASK_UPDATE_REQUEST";
export const TASK_UPDATE_SUCCESS = "TASK_UPDATE_SUCCESS";
export const TASK_UPDATE_FAILURE = "TASK_UPDATE_REQUEST";

export const TASK_DELETE_REQUEST = "TASK_DELETE_REQUEST";
export const TASK_DELETE_SUCCESS = "TASK_DELETE_SUCCESS";
export const TASK_DELETE_FAILURE = "TASK_DELETE_REQUEST";