export const WORKSPACE_CREATE_REQUEST = "WORKSPACE_CREATE_REQUEST";
export const WORKSPACE_CREATE_SUCCESS = "WORKSPACE_CREATE_SUCCESS";
export const WORKSPACE_CREATE_FAILURE = "WORKSPACE_CREATE_REQUEST";